### ISSUE TITLE
Board Support Request : Does it support Waveshare and Seeed Studio ESP boards ?

### ISSUE THREAD

**Issue by sk9la** [Spooks4576/Ghost_ESP#13]
HI,

I just discoverd your project and it looks cool.

However I'm lost with the releases types, there are many and I don't know which one fit the below boards I use.
I have multiple ESP board:
- Wemos D1 Mini ESP32-WROOM
- Seeed Studio Xiao ESP32C6
- Waveshare ESP32-S3 Pico
- Waveshare ESP32-S3 Mini

**Comment by Spooks4576** [comment]
I can definitely add those boards for you I technically already have support for the WROOM and the C6 (C6 I Still got to Update the branch)

as for the S3 its a real hit or miss in terms of support so for those id recommend compiling the firmware for yourself using platformio as support for those highly depends if the board configurations are on platformio's registry 


I Will work on releasing a more generic release for the different types of ESP's instead of for specific board types

so until then ill keep this issue open thank you...

**Comment by Spooks4576** [comment]
Just Updated the latest release with a bunch of generic board types for the S2 WROOM S3 Mini C3's etc 

please take a look when you can i will update the C6 branch when i can 

i will leave this issue open in case you have any other questions if not i will close this issue after 24 hours

Thank you

**Comment by Spooks4576** [comment]
yes it can

**Comment by Spooks4576** [comment]
im closing this issue please reopen this if you have any further issues
