### ISSUE TITLE
3 in 1 multiboard support needed

### ISSUE THREAD

**Issue by Neo2a** [Spooks4576/Ghost_ESP#130]
Hello,
Please guide me how can I flash 3in1 multiboard card with Ghost_ESP firmware.
[https://www.youtube.com/watch?v=Mnv05jEKFvA](url)
Thank you
Steve

**Comment by Spooks4576** [comment]
you will need to follow the manual flash guide located here 

https://github.com/Spooks4576/Ghost_ESP/wiki/Installation#usb-connection-method


that video you sent also explains how to do it so you should be good to go 

that being said since its a ESP32-S2 (Basing this off the video)

you will need to download the /esp32s2-generic.zip from releases 

here is the full link

https://github.com/Spooks4576/Ghost_ESP/releases/download/VA1.4.5/esp32s2-generic.zip

If you have further questions or need further help with flashing be sure to join the discord located at 
https://ghostesp.net
