### ISSUE TITLE
Does not support CYD ESP32-2432S024

### ISSUE THREAD

**Issue by Asmodeux2** [Spooks4576/Ghost_ESP#71]
![20241106_132813](https://github.com/user-attachments/assets/e91e8df0-e3ad-4fee-87b8-7285112737c8)
Stably works only on ESP32-2432S028 which is 2.8 inches.
On ESP32-2432S024 which is 2.4 inches - does not work

**Comment by Spooks4576** [comment]
this is the USB C Version correct? it should work if you flash that variant

also if it doesn't work its gonna be hard for me to verify that any fixes i do would work since i don't have that CYD Model and don't plan on supporting it right now 

the only CYD Variants i support is 

Micro USB 
Dual USB 
And USB C 2.8 inch 

Maybe in the future ill begin supporting more CYDs but there's too many rn to count

**Comment by Asmodeux2** [comment]
Buddy, I understand the confusion, but the ESP32-2432S024C module has a CST820 sensor. It simply won't work because this library is not declared. Please confirm that this firmware is only for the ESP32-2432S028.

**Comment by Asmodeux2** [comment]
Не подтвердите а укажите в тексте чтобы другие не путались

**Comment by Spooks4576** [comment]
> Buddy, I understand the confusion, but the ESP32-2432S024C module has a CST820 sensor. It simply won't work because this library is not declared. Please confirm that this firmware is only for the ESP32-2432S028.

i plan to be more transparent in the future about what CYDs specifically work with this firmware thank you
