### ISSUE TITLE
Not work touch display on ESP32-2432S024C

### ISSUE THREAD

**Issue by Asmodeux2** [Spooks4576/Ghost_ESP#85]
**You are a wizard**, you made the firmware for ESP32-2432S024(R), thank you very much. But can you make a firmware for **ESP32-2432S024(C)** it uses **CST820** library for touch screen. Thank you very much in advance!

**Comment by Asmodeux2** [comment]
![20241115_170402.jpg](https://github.com/user-attachments/assets/ed53319e-0d37-437d-a7b0-5da2ac25430f)

**Comment by Asmodeux2** [comment]
[Library CST820 for touch display ESP32-2432S024C](https://github.com/codekulturbonn/espocto/blob/refs%2Fheads%2Fmain/src%2FCST820.h)

**Comment by Spooks4576** [comment]
> [Library CST820.h for touch display ESP32-2432S024C](https://github.com/codekulturbonn/espocto/blob/refs%2Fheads%2Fmain/src%2FCST820.h)
> 
> [Library CST820.cpp for touch display ESP32-2432S024C](https://github.com/codekulturbonn/espocto/blob/main/src%2FCST820.cpp)

i can def add support for this however my only issue is i wont be able to confirm if it works or not without you contacting me on discord @ spooky4576 also this is because i am against releasing stuff without being able to verify it working first 

so if you really want this supported please contact me on discord thanks

**Comment by Asmodeux2** [comment]
You use Telegram?

**Comment by Spooks4576** [comment]
> You use Telegram?

yes one sec
